{% set name = "pytest-doctestplus" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-doctestplus-{{ version }}.tar.gz
  sha256: f884e2231fe5378cc8e5d1a272d19b01ebd352df0591a5add55ff50adac2d2d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - pip
    - pytest >=4.6
    - packaging >=17.0
    - python >=3.7
    - setuptools >=30.3

test:
  imports:
    - pytest_doctestplus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scientific-python/pytest-doctestplus
  summary: Pytest plugin with advanced doctest features.
  description: |
    This package contains a plugin for the pytest framework that provides
    advanced doctest support and enables the testing of reStructuredText files.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  doc_url: https://pypi.org/project/pytest-doctestplus/
  dev_url: https://github.com/scientific-python/pytest-doctestplus

extra:
  recipe-maintainers:
    - anthchirp
    - astrofrog-conda-forge
    - pllim
    - mwcraig
